version: '3'
services: 
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    # stdin_open: true
    tty: true
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development