version: '3'
services: 
  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    command: python api/main.py
    ports:
      - 8000:8000
    tty: true
    volumes:
      - './backend:/api/:cached'
    environment:
      PYTHONPATH: .

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    # stdin_open: true
    tty: true
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development