# See:
# https://docs.github.com/en/actions/guides/building-and-testing-python
# https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
name: Python lint and tests in backend

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r devel-requirements.txt

      - name: Run Black
        working-directory: backend
        run: |
          black .

      - name: Run Lint with flake8
        working-directory: backend
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        env:
          PYTHONPATH: "./backend"
        run: |
          # See:
          # https://pytest-vcr.readthedocs.io/en/latest/configuration/
          pytest . --vcr-record=none
