# See:
# https://docs.github.com/en/actions/guides/building-and-testing-python
# https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
name: CI in backend

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up uv cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('backend/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        working-directory: backend
        run: |
          uv sync --extra dev

      - name: Run ruff format check
        working-directory: backend
        run: |
          uv run ruff format --check api/

      - name: Run ruff lint
        working-directory: backend
        run: |
          uv run ruff check api/

      # FIXME: Fix type errors
      # - name: Run type check with mypy
      #   working-directory: backend
      #   run: |
      #     uv run mypy api/

      - name: Test with pytest
        working-directory: backend
        run: |
          uv run pytest tests/ --vcr-record=none
