# See:
# https://docs.github.com/en/actions/guides/building-and-testing-python
# https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
name: CI in backend

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Install uv with Python 3.12
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
          enable-cache: true
          working-directory: backend

      - name: Install dependencies
        working-directory: backend
        run: |
          make install

      - name: Run format check
        working-directory: backend
        run: |
          make fmt

      - name: Run lint
        working-directory: backend
        run: |
          make lint

      - name: Run type check
        working-directory: backend
        run: |
          make check

      - name: Run tests
        working-directory: backend
        run: |
          make test
