# See:
# https://docs.github.com/en/actions/guides/building-and-testing-nodejs#building-and-testing-your-code
name: CI in frontend

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: frontend
        run: |
          yarn install

      - name: Build
        working-directory: frontend
        run: |
          yarn build

      - name: Lint
        working-directory: frontend
        run: |
          yarn lint

      # TODO: Test
      # - name: Test
      #   working-directory: frontend
      #   run: |
      #     yarn test

      # TODO: Integration Test